"""
Bind the published lineage artifact to the project's own rules.

`docs/lineage.json` is regenerated by every build and committed. These tests
assert the things the README relies on being true of it. They read the committed
artifact, so they run in CI without the dataset.

The important one is `test_every_test_is_tagged_with_a_quality_dimension`. The
scorecard's premise is that every test maps to a quality dimension; without this
test, someone adds an untagged test, the scorecard quietly files it under
'untagged', and the published coverage overstates itself. This is the same
documentation-bound-to-reality idea as project 1's test_docs.py.
"""

import json
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
LINEAGE = json.loads((ROOT / "docs" / "lineage.json").read_text())

DIMENSIONS = {
    "completeness", "validity", "accuracy",
    "consistency", "timeliness", "uniqueness",
}


def test_lineage_artifact_is_not_empty():
    assert LINEAGE["counts"]["models"] > 0
    assert LINEAGE["counts"]["tests"] > 0


def test_counts_match_the_listed_nodes():
    """A count that disagrees with its own list means the exporter is lying."""
    assert LINEAGE["counts"]["models"] == len(LINEAGE["models"])
    assert LINEAGE["counts"]["tests"] == len(LINEAGE["tests"])


@pytest.mark.parametrize("test", LINEAGE["tests"], ids=lambda t: t["name"])
def test_every_test_is_tagged_with_a_quality_dimension(test):
    """Every dbt test must declare which quality dimension it evidences.

    An untagged test still runs, but it contributes nothing to the scorecard
    while looking like coverage. If this fails, add a
    `meta: {dq_dimension: ...}` block to the test's config.
    """
    assert test["dq_dimension"] in DIMENSIONS, (
        f"{test['name']} is tagged '{test['dq_dimension']}', "
        f"which is not one of the six standard dimensions"
    )


@pytest.mark.parametrize("model", LINEAGE["models"], ids=lambda m: m["name"])
def test_every_model_has_a_description(model):
    """A model nobody described is a model nobody has to justify."""
    assert model["description"], f"{model['name']} has no description"


@pytest.mark.parametrize("model", LINEAGE["models"], ids=lambda m: m["name"])
def test_every_model_declares_its_grain(model):
    """The project's central discipline: state the grain, in writing, per model."""
    assert "grain" in model["description"].lower(), (
        f"{model['name']}'s description does not state its grain"
    )


@pytest.mark.parametrize(
    "model", [m for m in LINEAGE["models"] if m["name"].startswith("stg_")],
    ids=lambda m: m["name"],
)
def test_staging_models_read_from_sources_not_other_models(model):
    """Staging is one model per source: rename, cast, deduplicate. A staging
    model that depends on another model has business logic in the wrong layer."""
    assert model["sources"], f"{model['name']} reads from no source"
    assert not model["depends_on"], (
        f"{model['name']} depends on {model['depends_on']}; staging models "
        f"should read only from sources"
    )


def test_every_model_is_materialized_deliberately():
    """Staging is views, marts are tables. Anything else is an accident."""
    for model in LINEAGE["models"]:
        expected = "view" if model["name"].startswith("stg_") else "table"
        assert model["materialized"] == expected, (
            f"{model['name']} is materialized as {model['materialized']}, "
            f"expected {expected}"
        )
