"""
Profile the raw layer before any modelling happens.

Writes `docs/profile_raw.md`. Output is deterministic -- sorted, no timestamps --
so it can be committed and re-checked by CI like every other generated artifact.

The point of profiling first is that a staging model written from a data
dictionary rather than from the data will silently encode whatever the
dictionary got wrong. Everything asserted about this dataset in the README
should trace back to a number in this file.
"""

import sys
from pathlib import Path

import duckdb

ROOT = Path(__file__).resolve().parents[1]
DB = ROOT / "data" / "olist.duckdb"
OUT = ROOT / "docs" / "profile_raw.md"

TABLES = [
    "orders", "order_items", "customers", "products", "sellers",
    "order_reviews", "order_payments", "geolocation",
    "product_category_name_translation",
]

# (child table, child column, parent table, parent column)
REFERENTIAL = [
    ("order_items", "order_id", "orders", "order_id"),
    ("order_items", "product_id", "products", "product_id"),
    ("order_items", "seller_id", "sellers", "seller_id"),
    ("orders", "customer_id", "customers", "customer_id"),
    ("order_reviews", "order_id", "orders", "order_id"),
    ("order_payments", "order_id", "orders", "order_id"),
    ("products", "product_category_name", "product_category_name_translation",
     "product_category_name"),
]

# Candidate keys we expect to be unique, and want to find out about if they aren't.
CANDIDATE_KEYS = [
    ("orders", ["order_id"]),
    ("customers", ["customer_id"]),
    ("products", ["product_id"]),
    ("sellers", ["seller_id"]),
    ("order_items", ["order_id", "order_item_id"]),
    ("order_reviews", ["review_id"]),
    ("order_payments", ["order_id", "payment_sequential"]),
    ("geolocation", ["geolocation_zip_code_prefix"]),
    ("product_category_name_translation", ["product_category_name"]),
]


def main() -> int:
    if not DB.exists():
        print(f"ERROR: {DB} not found. Run scripts/load_raw.py first.")
        return 1

    con = duckdb.connect(str(DB), read_only=True)
    lines = [
        "# Raw layer profile",
        "",
        "Generated by `scripts/profile_raw.py` from `data/olist.duckdb`.",
        "Do not edit by hand -- regenerate it.",
        "",
        "Every column is VARCHAR at this layer by design; see `scripts/load_raw.py`.",
        "`empty` counts zero-length strings, which are *not* NULL but almost always",
        "mean the same thing, and which a naive null check misses entirely.",
        "",
        "## Column profile",
        "",
    ]

    for t in TABLES:
        rows = con.execute(f"select count(*) from raw.{t}").fetchone()[0]
        cols = [r[0] for r in con.execute(f"describe raw.{t}").fetchall()]
        lines += [
            f"### `raw.{t}` — {rows:,} rows",
            "",
            "| column | nulls | null % | empty | distinct |",
            "|---|---:|---:|---:|---:|",
        ]
        for c in cols:
            n_null, n_empty, n_distinct = con.execute(
                f'''select
                        count(*) filter (where "{c}" is null),
                        count(*) filter (where "{c}" = ''),
                        count(distinct "{c}")
                    from raw.{t}'''
            ).fetchone()
            pct = (n_null / rows * 100) if rows else 0.0
            lines.append(f"| `{c}` | {n_null:,} | {pct:.2f}% | {n_empty:,} | {n_distinct:,} |")
        lines.append("")

    lines += ["## Candidate key uniqueness", "",
              "| table | candidate key | rows | distinct | duplicate rows |",
              "|---|---|---:|---:|---:|"]
    for t, keys in CANDIDATE_KEYS:
        key_sql = ", ".join(f'"{k}"' for k in keys)
        rows, distinct = con.execute(
            f"select count(*), count(distinct ({key_sql})) from raw.{t}"
        ).fetchone()
        dupes = rows - distinct
        flag = "" if dupes == 0 else f" **{dupes:,}**"
        lines.append(
            f"| `{t}` | `{', '.join(keys)}` | {rows:,} | {distinct:,} |"
            f"{flag if dupes else ' 0'} |"
        )
    lines.append("")

    lines += ["## Referential integrity", "",
              "Orphans are child rows whose key has no match in the parent table.",
              "",
              "| child | column | parent | orphan rows | orphan % | distinct orphan keys |",
              "|---|---|---|---:|---:|---:|"]
    for child, col, parent, pcol in REFERENTIAL:
        total = con.execute(f"select count(*) from raw.{child}").fetchone()[0]
        orphans, distinct_orphans = con.execute(
            f'''select count(*), count(distinct c."{col}")
                from raw.{child} c
                left join raw.{parent} p on c."{col}" = p."{pcol}"
                where p."{pcol}" is null and c."{col}" is not null'''
        ).fetchone()
        pct = (orphans / total * 100) if total else 0.0
        lines.append(
            f"| `{child}` | `{col}` | `{parent}` | {orphans:,} | {pct:.2f}% | {distinct_orphans:,} |"
        )
    lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    con.close()
    print(f"Wrote {OUT.relative_to(ROOT)} ({len(lines)} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
